In [ ]:
import pandas as pd
df = pd.read_csv('/content/Customer Purchase.csv')
df.head()

   Age  Gender Education   Review Purchased
0   30  Female    School  Average        No
1   68  Female        UG     Poor        No
2   70  Female        PG     Good        No
3   72  Female        PG     Good        No
4   16  Female        UG  Average        No

In [ ]:
#checking missing values
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        50 non-null     int64
 1   Gender     50 non-null     object
 2   Education  50 non-null     object
 3   Review     50 non-null     object
 4   Purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [ ]:
df['Review'].value_counts()

Review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [ ]:
df['Education'].value_counts()

Education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [ ]:
#separarting ordinal categorical variable
df1=df.iloc[:,2:4]
df1.head(2)

  Education   Review
0    School  Average
1        UG     Poor

In [ ]:
#implementing ordinal encoding on df1
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder(categories=[['School','UG','PG'],['Poor','Average','Good']])

In [ ]:
df1_oe=oe.fit_transform(df1)
df1_oe

array([[0., 1.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [1., 2.]])

In [ ]:
print(type(df1_oe))

<class 'numpy.ndarray'>

In [ ]:
df1=pd.DataFrame(df1_oe,columns=['Education','Review'])
df1.head()

   Education  Review
0        0.0     1.0
1        1.0     0.0
2        2.0     2.0
3        2.0     2.0
4        1.0     1.0

In [ ]:
df1=df1.astype(int)
df1.head(2)

   Education  Review
0          0       1
1          1       0

In [ ]:
df2=df[['Gender','Purchased']]
df2.head()

   Gender Purchased
0  Female        No
1  Female        No
2  Female        No
3  Female        No
4  Female        No

In [ ]:
#first appling pd.get_dummies
dummy_df=pd.get_dummies(df2)
dummy_df.head(2)

   Gender_Female  Gender_Male  Purchased_No  Purchased_Yes
0           True        False          True          False
1           True        False          True          False

In [ ]:
#integer
dummy_df=dummy_df.astype(int)
dummy_df.head(2)

   Gender_Female  Gender_Male  Purchased_No  Purchased_Yes
0              1            0             1              0
1              1            0             1              0

In [ ]:
#onehotencoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
oh_enc=OneHotEncoder(sparse_output=False)
#it provide output in array format

In [ ]:
oh_enc_arr=oh_enc.fit_transform(df2)
oh_enc_arr

array([[1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [ ]:
oh_enc=OneHotEncoder(sparse_output=False, drop='first')
#it provide output in array format

In [ ]:
oh_enc_arr=oh_enc.fit_transform(df2)
oh_enc_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.]])

In [ ]:
df2=pd.DataFrame(oh_enc_arr,columns=['Gender','Purchased'])
df2.head()

   Gender  Purchased
0     0.0        0.0
1     0.0        0.0
2     0.0        0.0
3     0.0        0.0
4     0.0        0.0

In [ ]:
df2=df2.astype(int)
df2.head(2)

   Gender  Purchased
0       0          0
1       0          0